# Generated by Django 3.2.19 on 2023-06-19 12:19

import My_music_app_project.my_music_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_music_app', '0003_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), My_music_app_project.my_music_app.models.validate_only_letters_nums_or_underscore]),
        ),
    ]
